### ISSUE TITLE
Api issue method GET /api/badge-type & GET /api/rules

### ISSUE THREAD

**Issue by MichaelRohrer** [ltouroumov/amt-g4mify#2]
ERROR: 
{
  "timestamp": 1481800939603,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.dao.InvalidDataAccessApiUsageException",
  "message": "You're trying to execute a streaming query method without a surrounding transaction that keeps the connection open so that the Stream can actually be consumed. Make sure the code consuming the stream uses @Transactional or any other way of declaring a (read-only) transaction.",
  "path": "/api/rules"
}

**Comment by ltouroumov** [comment]
Fixed in 123e60b6c26538299b664dcf008d1edbd1b0d472
